version: '3.1'
services:
  app:
    container_name: oliy-mahad:1.0
    image: oliy-mahad:1.0
    build: ./
    ports:
      - "9090:8080"
    volumes:
      - "$PWD:/test_volume"
    depends_on:

      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task
